#!/usr/bin/env ruby

# TODO: Do things in ruby where possible instead of shelling out!

ignore 'doc', 'log', 'pkg', 'tmp', 'site', 'web', 'work'

# TODO: Eventually Fire should provide access to metadata via a utility method.
version = File.read('meta/version').strip

desc "update manifest"
task 'manifest' do
  system 'mast -u'
end

desc "release and tag"
task 'release' do
  exit -1 unless system('detroit release')
  system 'vclog-news | git tag -a -F - #{version}'
end

file 'meta' do
  system 'dotruby source meta'
end

file 'lib' do
  exit -1 unless system('detroit test')
end

file 'demo' do
  exit -1 unless system('detroit test')
end

=begin
state :create_project do
  ! File.exist?('.ruby')
  # gem install dotruby
end

rule :create_project do
  system '$EDITOR ruby.yaml'
  #break unless ask('creating new project?')
  #meta = YAML.load_file('ruby.yaml')
  #name = ARGV[1] || File.basename(Dir.pwd)
  #meta['name'] = name
  #meta.each do |k,v|
  #  case v2 = ask("#{k} (#{v}):")
  #  when nil, ''
  #  when '`' then exit
  #  when '!' then exit -1
  #  else
  #    meta[k] = YAML.load(v2)
  #  end
  #end
end
=end

